import type {Metadata} from "next";
import localFont from "next/font/local";
import "./index.css";
import {Button} from "@/components/ui/button";
import Link from "next/link";
import {Briefcase, Users} from "lucide-react";
import * as React from "react";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Healthcare",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="w-16 bg-[#1a2234] h-full p-4 flex flex-col items-center">
            <div className="space-y-8">
                <Button variant="ghost" className="w-full p-2" asChild>
                    <Link href="/">
                        <Users className="h-6 w-6 text-white"/>
                    </Link>
                </Button>
                <Button variant="ghost" className="w-full p-2" asChild>
                    <Link href="/">
                        <Briefcase className="h-6 w-6 text-white"/>
                    </Link>
                </Button>
            </div>
        </div>

        {children}
        </body>
        </html>
    );
}
